/// Flutter icons MyFlutterApp
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
/// * Web Symbols, Copyright (c) 2011 by Just Be Nice studio. All rights reserved.
///         Author:    Just Be Nice studio
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.justbenicestudio.com/
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';

  static const IconData check_circle = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData icon_list = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData icon_power = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData icon_shopping_cart = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData heart_empty = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData upload_cloud_outline = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData icon_heart_black = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData icon_notifications = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData icon_contact = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData icon_profile = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData icon_verification = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData basket = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData search = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData home = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData cart = const IconData(0xe82e, fontFamily: _kFontFam);
}
